AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SNSInvokerSchedule:
    Type: String
    Default: "rate(1 hour)"
    Description: "Rate for EventBridge Rule (exmaple: rate(5 minutes), rate(1 hour), cron(0 12 * * ? *))"

Resources:
  SNSPublisherLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SNSPublisherLambda
      Runtime: dotnet8
      Handler: SNSPublisherLambda::SNSPublisherLambda.Function::FunctionHandler
      Role: !GetAtt SNSPublisherLambdaExecutionRole.Arn
      Timeout: 10
      Environment:
        Variables:
          SNSTopicArn: !Ref LambdasSNSTopic
          SQSQueueUrl: !Ref LogsProcessingSQS
      Code:
        S3Bucket: cold-start-lambdas
        S3Key: SNSPublisherLambda.zip

  SNSPublisherLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SNSPublisherLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref LambdasSNSTopic
        - PolicyName: SQSSendMessagePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt LogsProcessingSQS.Arn

  SNSLambdaInvokerRule:
    Type: AWS::Events::Rule
    Properties:
      Name: SNSLambdaInvokerRule
      ScheduleExpression: !Ref SNSInvokerSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt SNSPublisherLambda.Arn
          Id: "LambdaTarget"
          RoleArn: !GetAtt SNSLambdaInvokerRulerRole.Arn
          
          
  SNSLambdaInvokerRulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SNSLambdaInvokerRulePermissionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: SNSLambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "lambda:InvokeFunction"
                Resource: !GetAtt SNSPublisherLambda.Arn
                
  LambdasSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: LambdasSNSTopic
      Subscription:
      ### dotnet
        - Endpoint: !GetAtt TestingLambdaDotnet.Arn
          Protocol: lambda
      ### java
        - Endpoint: !GetAtt TestingLambdaJava.Arn
          Protocol: lambda
      ### node
        - Endpoint: !GetAtt TestingLambdaNode.Arn
          Protocol: lambda
      ### python
        - Endpoint: !GetAtt TestingLambdaPython.Arn
          Protocol: lambda
      ### ruby
        - Endpoint: !GetAtt TestingLambdaRuby.Arn
          Protocol: lambda
      
          
### dotnet          
  TestingLambdaDotnetSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TestingLambdaDotnet
      Principal: sns.amazonaws.com
      SourceArn: !Ref LambdasSNSTopic
      
  TestingLambdaDotnet:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TestingLambdaDotnet
      Runtime: dotnet6
      Handler: TestingLambdaDotnet::TestingLambdaDotnet.Function::FunctionHandler
      Role: !GetAtt TestingLambdaDotnetExecutionRole.Arn
      Timeout: 10
      Code:
        S3Bucket: cold-start-lambdas
        S3Key: TestingLambdaDotnet.zip

  TestingLambdaDotnetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TestingLambdaDotnetExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
### Java          
  TestingLambdaJavaSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TestingLambdaJava
      Principal: sns.amazonaws.com
      SourceArn: !Ref LambdasSNSTopic
      
  TestingLambdaJava:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TestingLambdaJava
      Runtime: java11
      Handler: org.example.Handler::handleRequest
      Role: !GetAtt TestingLambdaJavaExecutionRole.Arn
      Timeout: 10
      Code:
        S3Bucket: cold-start-lambdas
        S3Key: TestingLambdaJava.zip

  TestingLambdaJavaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TestingLambdaJavaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
### Node          
  TestingLambdaNodeSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TestingLambdaNode
      Principal: sns.amazonaws.com
      SourceArn: !Ref LambdasSNSTopic
      
  TestingLambdaNode:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TestingLambdaNode
      Runtime: nodejs18.x
      Handler: TestingLambdaNode.handler
      Role: !GetAtt TestingLambdaNodeExecutionRole.Arn
      Timeout: 10
      Code:
        S3Bucket: cold-start-lambdas
        S3Key: TestingLambdaNode.zip

  TestingLambdaNodeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TestingLambdaNodeExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
### Python          
  TestingLambdaPythonSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TestingLambdaPython
      Principal: sns.amazonaws.com
      SourceArn: !Ref LambdasSNSTopic
      
  TestingLambdaPython:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TestingLambdaPython
      Runtime: python3.11
      Handler: TestingLambdaPython.lambda_handler
      Role: !GetAtt TestingLambdaPythonExecutionRole.Arn
      Timeout: 10
      Code:
        S3Bucket: cold-start-lambdas
        S3Key: TestingLambdaPython.zip

  TestingLambdaPythonExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TestingLambdaPythonExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
### Ruby          
  TestingLambdaRubySNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TestingLambdaRuby
      Principal: sns.amazonaws.com
      SourceArn: !Ref LambdasSNSTopic
      
  TestingLambdaRuby:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TestingLambdaRuby
      Runtime: ruby3.2
      Handler: TestingLambdaRuby.lambda_handler
      Role: !GetAtt TestingLambdaRubyExecutionRole.Arn
      Timeout: 10
      Code:
        S3Bucket: cold-start-lambdas
        S3Key: TestingLambdaRuby.zip

  TestingLambdaRubyExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TestingLambdaRubyExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
### end
    
  LogsProcessingSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: LogsProcessingQueue
      DelaySeconds: 120
      
  LogsProcessingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LogsProcessingLambda
      Runtime: dotnet8
      Handler: LogsProcessingLambda::LogsProcessingLambda.Function::FunctionHandler
      Role: !GetAtt LogsProcessingLambdaExecutionRole.Arn
      Timeout: 10
      Code:
        S3Bucket: cold-start-lambdas
        S3Key: LogsProcessingLambda.zip
        
  LogsProcessingLambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt LogsProcessingSQS.Arn
      FunctionName: !GetAtt LogsProcessingLambda.Arn
            
  LogsProcessingLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LogsProcessingLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                  - "logs:GetLogEvents"
                Resource: "*"
        - PolicyName: S3ObjectsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:DeleteObject
                Resource: arn:aws:s3:::testing-lambdas-logs/*
        - PolicyName: S3BucketPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                    - s3:ListBucket
                Resource: arn:aws:s3:::testing-lambdas-logs
        - PolicyName: SQSQueuePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt LogsProcessingSQS.Arn
  