name: Build and deploy infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: general

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check AWS cli
        run: aws --version

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Build LogsProcessingLambda
        working-directory: ./aws/lambdas/LogsProcessingLambda
        run: pwsh ./build_application.ps1
        shell: pwsh

      - name: Build SNSPublisherLambda
        working-directory: ./aws/lambdas/SNSPublisherLambda
        run: pwsh ./build_application.ps1
        shell: pwsh

      - name: Build TestingLambdaDotnet
        working-directory: ./aws/lambdas/TestingLambdaDotnet
        run: pwsh ./build_application.ps1
        shell: pwsh

      - name: Deploy LogsProcessingLambda
        working-directory: ./aws/lambdas/LogsProcessingLambda
        run: pwsh ./deploy_application.ps1
        shell: pwsh

      - name: Deploy SNSPublisherLambda
        working-directory: ./aws/lambdas/SNSPublisherLambda
        run: pwsh ./deploy_application.ps1
        shell: pwsh

      - name: Deploy TestingLambdaDotnet
        working-directory: ./aws/lambdas/TestingLambdaDotnet
        run: pwsh ./deploy_application.ps1
        shell: pwsh

      - name: Deploy cloudformation
        working-directory: ./aws/deployment
        run: pwsh ./deploy_stack.ps1
        shell: pwsh
